# Ansi color code variables
r="\e[0;91m"
b="\e[0;94m"
b_bg="\e[0;104m${expand_bg}"
r_bg="\e[0;101m${expand_bg}"
g_bg="\e[0;102m${expand_bg}"
g="\e[0;92m"
white="\e[0;97m"
u="\e[4m"
re="\e[0m"
echo -e "${b}===== blue =====${re}"
echo -e "${b_bg}===== blue =====${re}"
echo -e "${b}${u}===== blue =====${re}"
echo ""
echo -e "${r}===== red =====${re}"
echo -e "${r_bg}===== red =====${re}"
echo -e "${r}${u}===== red =====${re}"
